# ASSIGNMENT 3

# Task 1

Q1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [2]:
try:
    a = 5/0
    print('Calculating a')
except:
    print('Formula for "a" is not working!')

Formula for "a" is not working!


In [5]:
try: 
    a = 5/0
    print('Calculating a')
except Exception as e:
    print(e)

division by zero


Q2. Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [6]:
def sentences():
    subjects = ["Americans","Indians"]
    verbs = ["play","watch"]
    objects = ["baseball","cricket"]
    for i in subjects:
        for j in verbs:
            for k in objects:
                print(i,j,k)
                
sentences()

Americans play baseball
Americans play cricket
Americans watch baseball
Americans watch cricket
Indians play baseball
Indians play cricket
Indians watch baseball
Indians watch cricket


# Task 2

Q1. Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [2]:
import numpy as np
in_vector = [1,2,3,4,5,6,7,8]
def theo(in_vec, increasing=True):
    l = (len(in_vec)/2)
    if increasing:
        out_mat = np.array([x**i for x in in_vec for i in np.arange(l, dtype=int) ])
        out_mat = out_mat.reshape(len(in_vec),l)
    else:
        out_mat = np.array([x**(l-1-i) for x in in_vec for i in np.arange(l,dtype=int)])
        out_mat = out_mat.reshape(len(in_vec),l)
    return out_mat

print('Vander matrix for increasing boolean argument:\n\n',theo(in_vector,True))
print('\nVander matrix for decreasing boolean argument:\n\n',theo(in_vector,False))

Vander matrix for increasing boolean argument:

 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]
 [  1   6  36 216]
 [  1   7  49 343]
 [  1   8  64 512]]

Vander matrix for decreasing boolean argument:

 [[   1.    1.    1.    1.]
 [   8.    4.    2.    1.]
 [  27.    9.    3.    1.]
 [  64.   16.    4.    1.]
 [ 125.   25.    5.    1.]
 [ 216.   36.    6.    1.]
 [ 343.   49.    7.    1.]
 [ 512.   64.    8.    1.]]


C:\Users\User1\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\User1\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
