Q1. Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

Q2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [5]:
import numpy as np
in_vector = [8,7,6,5,4,3,2,1]
def theo(in_vec, increasing=True):
    l = (len(in_vec)/2)
    if increasing:
        out_mat = np.array([x**i for x in in_vec for i in np.arange(l, dtype=int) ])
        out_mat = out_mat.reshape(len(in_vec),l)
    else:
        out_mat = np.array([int(x**(l-1-i)) for x in in_vec for i in np.arange(l,dtype=int)])
        out_mat = out_mat.reshape(len(in_vec),l)
    return out_mat

print('Vander matrix for increasing boolean argument:\n\n',theo(in_vector,True))
print('\nVander matrix for decreasing boolean argument:\n\n',theo(in_vector,False))

Vander matrix for increasing boolean argument:

 [[  1   8  64 512]
 [  1   7  49 343]
 [  1   6  36 216]
 [  1   5  25 125]
 [  1   4  16  64]
 [  1   3   9  27]
 [  1   2   4   8]
 [  1   1   1   1]]

Vander matrix for decreasing boolean argument:

 [[512  64   8   1]
 [343  49   7   1]
 [216  36   6   1]
 [125  25   5   1]
 [ 64  16   4   1]
 [ 27   9   3   1]
 [  8   4   2   1]
 [  1   1   1   1]]


C:\Users\User1\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\User1\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [6]:
def moving_average(a, n) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
    
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
moving_average(a,3)

array([   5.        ,    4.66666667,    5.66666667,    6.66666667,
          9.66666667,   28.66666667,   49.33333333,   72.66666667,
         84.        ,   93.33333333,  116.33333333])